# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# output directory, generated dynamically on each run
run:
  #  dir: ${paths.log_dir}/${task_name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
  dir: ${paths.log_dir}/${task_name}/runs/baseline_3d_unet_${data.img_size[0]}_bs${data.batch_size}_d4_pseudo_${model.net.dropout}_random/${data.fold}

sweep:
  #  dir: ${paths.log_dir}/${task_name}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
  dir: ${paths.log_dir}/${task_name}/multiruns/baseline3d_unet_${data.img_size[0]}_bs${data.batch_size}_d4_pseudo_${model.net.dropout}_random/${data.fold}
  subdir: ${hydra.job.num}

job_logging:
  handlers:
    file:
      # Incorporates fix from https://github.com/facebookresearch/hydra/pull/2242
      filename: ${hydra.runtime.output_dir}/${task_name}.log
