defaults:
  - model_checkpoint
  - model_summary
  - rich_progress_bar
  - lr_logger
  #  - lr_finder
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}_dice_{val/dice:.4f}"
  monitor: "val/dice"
  #  monitor: "val/sd@0.3"
  mode: "max"
  save_last: True
  auto_insert_metric_name: False
  save_top_k: 3

model_summary:
  max_depth: 0
